# Generated by Django 5.2.4 on 2025-07-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('HOSPITAL_ADMIN', 'Hospital Admin')], default='PATIENT', max_length=15),
        ),
    ]
